spring:
  r2dbc:
    url: ${R2DBC_DATABASE_URL:r2dbc:postgresql://localhost:5432/cat-shop}
    username: ${R2DBC_DATABASE_USERNAME:postgres}
    password: ${R2DBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    pool:
      max-size: 100
  docker:
    compose:
      lifecycle-management: start-only
springdoc:
  pathsToMatch: /api/**
